import sortAssembly from './sortAssembly'

describe('sortAssembly', () => {
    test('main', () => {
    const assembly = {
      ok                        : 'ASSEMBLY_COMPLETED',
      message                   : 'The Assembly was successfully completed.',
      assembly_id               : '7828446e5acd4aa996dce3455ec914e9',
      parent_id                 : null,
      account_id                : '4ce4fb3d9d1842b6ba5d6f3ccee4b066',
      template_id               : null,
      instance                  : 'jenks.transloadit.com',
      assembly_url              : 'http://api2.jenks.transloadit.com/assemblies/7828446e5acd4aa996dce3455ec914e9',
      assembly_ssl_url          : 'https://api2-jenks.transloadit.com/assemblies/7828446e5acd4aa996dce3455ec914e9',
      uppyserver_url            : 'https://api2-jenks.transloadit.com/companion/',
      companion_url             : 'https://api2-jenks.transloadit.com/companion/',
      websocket_url             : 'https://api2-jenks.transloadit.com/ws20074',
      tus_url                   : 'https://api2-jenks.transloadit.com/resumable/files/',
      bytes_received            : 486608,
      bytes_expected            : 486608,
      upload_duration           : 2.814,
      client_agent              : null,
      client_ip                 : null,
      client_referer            : null,
      transloadit_client        : 'node-sdk:2.0.8',
      start_date                : '2020/01/09 12:02:06 GMT',
      upload_meta_data_extracted: true,
      warnings                  : [],
      is_infinite               : false,
      has_dupe_jobs             : false,
      execution_start           : '2020/01/09 12:02:08 GMT',
      execution_duration        : 5.281,
      queue_duration            : 0.184,
      jobs_queue_duration       : 0.01,
      notify_start              : null,
      notify_url                : null,
      notify_status             : null,
      notify_response_code      : null,
      notify_duration           : null,
      last_job_completed        : '2020/01/09 12:02:14 GMT',
      fields                    : {},
      running_jobs              : [],
      bytes_usage               : 1097155,
      executing_jobs            : [],
      started_jobs              : [
        ':original:::original',
        'faces_detected:::original',
        'exported:::original',
        'exported::faces_detected',
      ],
      parent_assembly_status: null,
      params                : '{"steps":{":original":{"robot":"/upload/handle"},"faces_detected":{"use":":original","robot":"/image/facedetect","crop":true,"faces":"max-confidence","format":"preserve","crop_padding":"10%"},"exported":{"use":["faces_detected",":original"],"robot":"/s3/store","credentials":"demo_s3_credentials"}},"auth":{"key":"****","expires":"2020-01-10T12:02:05.826Z"}}',
      template              : null,
      merged_params         : '{"steps":{":original":{"robot":"/upload/handle"},"faces_detected":{"use":":original","robot":"/image/facedetect","crop":true,"faces":"max-confidence","format":"preserve","crop_padding":"10%"},"exported":{"use":["faces_detected",":original"],"robot":"/s3/store","credentials":"demo_s3_credentials"}},"auth":{"key":"****","expires":"2020-01-10T12:02:05.826Z"}}',
      expected_tus_uploads  : 1,
      started_tus_uploads   : 1,
      finished_tus_uploads  : 1,
      uploads               : [
        {
          id               : 'a30bd0776e7f4ac3817b056d102e8219',
          name             : 'joe-gardner-149699.jpg',
          basename         : 'joe-gardner-149699',
          ext              : 'jpg',
          size             : 485784,
          mime             : 'image/jpeg',
          type             : 'image',
          field            : 'file',
          md5hash          : 'fb205cb04b6998fe7ba364f70227cfa1',
          original_id      : 'a30bd0776e7f4ac3817b056d102e8219',
          original_basename: 'joe-gardner-149699',
          original_name    : 'joe-gardner-149699.jpg',
          original_path    : '/',
          original_md5hash : 'fb205cb04b6998fe7ba364f70227cfa1',
          from_batch_import: false,
          is_tus_file      : true,
          tus_upload_url   : 'https://api2-jenks.transloadit.com/resumable/files/f95ba7eebf22e0ebadcf9b09a3a91c65+DRCJv78IeFDneTwnYb3pagc8Bqg7IwlRAFpW8e3i.f4RSPIZXEeaxdheZiTBBvJ0pAyjxL3.U5TvUqWytvkObgz6Bh55biPZwLqzIK_mwRbjGl0UREMrju1zfy8.OgTg',
          url              : 'http://demos.transloadit.com.s3.amazonaws.com/a3/0bd0776e7f4ac3817b056d102e8219/joe-gardner-149699.jpg',
          ssl_url          : 'https://s3.amazonaws.com/demos.transloadit.com/a3/0bd0776e7f4ac3817b056d102e8219/joe-gardner-149699.jpg',
          meta             : {
            width             : 2500,
            height            : 1667,
            date_file_modified: '2020/01/09 12:02:08 GMT',
            aspect_ratio      : '1.500',
            has_clipping_path : false,
            frame_count       : 1,
            colorspace        : 'RGB',
            has_transparency  : false,
            average_color     : '#b09d96',
          },
        },
      ],
      results: {
        ':original': [
          {
            id               : 'a30bd0776e7f4ac3817b056d102e8219',
            name             : 'joe-gardner-149699.jpg',
            basename         : 'joe-gardner-149699',
            ext              : 'jpg',
            size             : 485784,
            mime             : 'image/jpeg',
            type             : 'image',
            field            : 'file',
            md5hash          : 'fb205cb04b6998fe7ba364f70227cfa1',
            original_id      : 'a30bd0776e7f4ac3817b056d102e8219',
            original_basename: 'joe-gardner-149699',
            original_name    : 'joe-gardner-149699.jpg',
            original_path    : '/',
            original_md5hash : 'fb205cb04b6998fe7ba364f70227cfa1',
            from_batch_import: false,
            is_tus_file      : false,
            tus_upload_url   : null,
            url              : 'http://demos.transloadit.com.s3.amazonaws.com/a3/0bd0776e7f4ac3817b056d102e8219/joe-gardner-149699.jpg',
            ssl_url          : 'https://s3.amazonaws.com/demos.transloadit.com/a3/0bd0776e7f4ac3817b056d102e8219/joe-gardner-149699.jpg',
            meta             : {
              width             : 2500,
              height            : 1667,
              date_file_modified: '2020/01/09 12:02:08 GMT',
              aspect_ratio      : '1.500',
              has_clipping_path : false,
              frame_count       : 1,
              colorspace        : 'RGB',
              has_transparency  : false,
              average_color     : '#b09d96',
            },
            queue    : 'live',
            queueTime: 0.01,
            execTime : 0.81,
            cost     : 97157,
          },
        ],
        faces_detected: [
          {
            id               : 'b8d12f6c517541ca86bf50c537cedb27',
            name             : 'joe-gardner-149699.jpg',
            basename         : 'joe-gardner-149699',
            ext              : 'jpg',
            size             : 141822,
            mime             : 'image/jpeg',
            type             : 'image',
            field            : 'file',
            md5hash          : '2a5cd917f4281b9438956e489c63dfd2',
            original_id      : 'a30bd0776e7f4ac3817b056d102e8219',
            original_basename: 'joe-gardner-149699',
            original_name    : 'joe-gardner-149699.jpg',
            original_path    : '/',
            original_md5hash : 'fb205cb04b6998fe7ba364f70227cfa1',
            from_batch_import: false,
            is_tus_file      : false,
            tus_upload_url   : null,
            url              : 'http://demos.transloadit.com.s3.amazonaws.com/b8/d12f6c517541ca86bf50c537cedb27/joe-gardner-149699.jpg',
            ssl_url          : 'https://s3.amazonaws.com/demos.transloadit.com/b8/d12f6c517541ca86bf50c537cedb27/joe-gardner-149699.jpg',
            meta             : {
              width             : 621,
              height            : 840,
              date_file_created : '2020/01/09 12:02:09 GMT',
              date_file_modified: '2020/01/09 12:02:12 GMT',
              aspect_ratio      : '0.739',
              has_clipping_path : false,
              frame_count       : 1,
              colorspace        : 'RGB',
              has_transparency  : false,
              average_color     : '#8d654d',
              faces             : [
                {
                  x1        : 981,
                  y1        : 121,
                  x2        : 1550,
                  y2        : 891,
                  height    : 840,
                  width     : 621,
                  confidence: 99.99,
                },
              ],
            },
            queue    : 'live',
            queueTime: 0,
            execTime : 0.83,
            cost     : 627606,
          },
        ],
      },
      build_id: '339',
    }
    const sorted = sortAssembly(assembly)
        expect(Object.keys(sorted)).toStrictEqual([
      'assembly_id',
      'ok',
      'message',
      'warnings',
      'account_id',
      'assembly_ssl_url',
      'assembly_url',
      'build_id',
      'bytes_expected',
      'bytes_received',
      'bytes_usage',
      'client_agent',
      'client_ip',
      'client_referer',
      'companion_url',
      'executing_jobs',
      'execution_duration',
      'execution_start',
      'expected_tus_uploads',
      'fields',
      'finished_tus_uploads',
      'has_dupe_jobs',
      'instance',
      'is_infinite',
      'jobs_queue_duration',
      'last_job_completed',
      'merged_params',
      'notify_duration',
      'notify_response_code',
      'notify_start',
      'notify_status',
      'notify_url',
      'params',
      'parent_assembly_status',
      'parent_id',
      'queue_duration',
      'running_jobs',
      'start_date',
      'started_jobs',
      'started_tus_uploads',
      'template',
      'template_id',
      'transloadit_client',
      'tus_url',
      'upload_duration',
      'upload_meta_data_extracted',
      'uppyserver_url',
      'websocket_url',
      'uploads',
      'results',
    ])
        expect(Object.keys(sorted.results)).toStrictEqual([
      ':original',
      'faces_detected',
    ])
    expect(Object.keys(sorted.uploads[0])).toStrictEqual([
      'id',
      'basename',
      'ext',
      'field',
      'from_batch_import',
      'is_tus_file',
      'md5hash',
      'mime',
      'name',
      'original_basename',
      'original_id',
      'original_md5hash',
      'original_name',
      'original_path',
      'size',
      'ssl_url',
      'tus_upload_url',
      'type',
      'url',
      'meta',
    ])
    expect(Object.keys(sorted.uploads[0].meta)).toStrictEqual([
      'aspect_ratio',
      'average_color',
      'colorspace',
      'date_file_modified',
      'frame_count',
      'has_clipping_path',
      'has_transparency',
      'height',
      'width',
    ])
  })
})
