const globby = require('globby')
const inflect = require('inflect')
const mkdirp = require('mkdirp')
const path = require('path')
const execa = require('execa')

const fsP = require('fs').promises
// const util = require('util')

const ROOT = `${__dirname}/..`
const SIMPLE = `${ROOT}/simple`

async function simpleToPackages () {
  const files = await globby([
    `${SIMPLE}/*.js`,
    `!${SIMPLE}/*.test.js`,
  ])

  for (const file of files) {
    const funcName = path.basename(file, '.js')
    const pkgName  = inflect.dasherize(inflect.underscore(funcName))
    const dirPath  = `${ROOT}/packages/${pkgName}`
    const pkgPath  = `${dirPath}/package.json`
    const entry    = `./index.js`

    console.log(`--> creating ${dirPath.replace(ROOT, '.')}`)
    await mkdirp(dirPath)

    const subfiles = await globby([`${SIMPLE}/${funcName}*.js`, `!${SIMPLE}/${funcName}*.test.js`])
    for (const subfile of subfiles) {
      const src = subfile
      const dst = `${dirPath}/index.js`

      console.log(`--> copying ${src.replace(ROOT, '.')} -> ${dst.replace(ROOT, '.')}`)
      const buf = `//\n// WARNING. DO NOT EDIT THIS FILE. EDIT IN ${src.replace(ROOT, '.')} INSTEAD\n//\n\n` + await fsP.readFile(src, 'utf-8')
      await fsP.writeFile(dst, buf, 'utf-8')
    }
    console.log(`--> writing ${pkgPath.replace(ROOT, '.')}`)

    const pkg = {
      name      : `@transloadit/${pkgName}`,
      repository: {
        type     : `git`,
        url      : `git://github.com/transloadit/monolib.git`,
        directory: `packages/${pkgName}`,
      },
      publishConfig: {
        registry: `https://npm.pkg.github.com/`,
      },
      main: entry,
    }

    await fsP.writeFile(`${pkgPath}`, JSON.stringify(pkg, null, '  '))
  }
}

async function publishPackages () {
  const files = await globby([
    `${ROOT}/packages/*/package.json`,
  ])
  for (const file of files) {
    const dirName = path.dirname(file)
    const cmd = `cd '${dirName}' && ((yarn && yarn publish); cd -)`
    console.log(cmd)
  }
}

async function main () {
  await simpleToPackages()
  await publishPackages()
}

main().catch(err => {
  console.error(err)
  process.exit(1)
})
