//
// WARNING. DO NOT EDIT THIS FILE. EDIT IN ./simple/file-exists.js INSTEAD
//

const fs             = require('fs')
module.exports = function fileExists (s) {
  return new Promise((resolve, reject) => {
    fs.access(s, fs.F_OK, (err) => {
      resolve(!err)
    })
  })
}
