name: Monolib CI

on:
  push:
    branches:
      - main
      - 'changeset-release/**'
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test (Node ${{ matrix.node-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 22
          - 24
    permissions:
      contents: read
      pull-requests: read

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: 🏗 Setup Caching
        uses: actions/cache@v4
        with:
          path: |
            **/node_modules
            .yarn/cache
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/yarn.lock', '**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node-version }}-

      - run: corepack yarn config set enableHardenedMode false
      - run: corepack yarn install --immutable

      - run: corepack yarn check
