name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'

      - name: 🏗 Setup Caching
        uses: actions/cache@v4
        with:
          path: |
            .turbo
            node_modules/.cache/turbo
            **/node_modules
            .yarn/cache
          key: ${{ runner.os }}-turbo-${{ hashFiles('**/yarn.lock', '**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      # Allow yarn to make changes during release
      - run: corepack yarn config set enableHardenedMode false
      - run: corepack yarn --mode=update-lockfile
      - run: corepack yarn build

      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          version: corepack yarn changeset version
          publish: corepack yarn release
          title: "chore: version packages"
          commit: "chore: version packages"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
